resources:
  pipelines:
    - pipeline: third-pipeline # Name of the pipeline resource
      source: first-pipeline  # Name of the target pipeline in Azure DevOps
      project: DevOpsCnS  # Required only if the source pipeline is in another project
      trigger: true  # Run target pipeline when any run of source pipeline completes

trigger:
- none

pool:
  name: self-hosted-agent

stages:
# Stage 1: Third Pipeline
- stage: ThirdPipeline
  displayName: Third Pipeline
  jobs:
  - job: ThirdPipelineJob
    displayName: Third Pipeline Job
    steps:
    - script: echo Hello Friends, Welcome  DevOps CnS Channel. This is Third Pipeline job!
      displayName: 'Run a one-line script from Third Pipeline job'
    
    - script: |
        echo "This is Demo Project"
        echo "You are learning how to create sequential pipeline in Azure DevOps"
        echo "where Third pipeline is triggered on completiong of Third pipeline"
      displayName: 'Run a Multi-line script variable Demo from Third Pipeline job'
